# Generated by Django 2.2.7 on 2019-11-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default=None, max_length=150, verbose_name='e-mail'),
        ),
    ]
